---
abstract: 'A simple LDAP-based credentials validation plugin for Net::Squid::Auth::Engine'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Squid-Auth-Plugin-SimpleLDAP
provides:
  Net::Squid::Auth::Plugin::SimpleLDAP:
    file: lib/Net/Squid/Auth/Plugin/SimpleLDAP.pm
    version: v0.1.81
requires:
  Net::LDAP: 0
  Scalar::Util: 0
  Test::More: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.1.81
