---
abstract: A simple LDAP-based credentials validation plugin for Net::Squid::Auth::Engine
author: 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Squid-Auth-Plugin-SimpleLDAP
no_index:
  directory:
    - inc
    - t
requires:
  Net::LDAP: 0
version: !!perl/hash:version
  original: 0.01.03
  qv: 1
  version:
    - 0
    - 1
    - 3
