#!/bin/bash

dry_run=0
[ "$1" = "-n" ] && dry_run=1

msg() {
  echo "$@" >&2
}

msg "== Making README"
( readme=../README
  [ "$dry_run" -eq 1 ] && readme=/dev/null 
  cd lib; perldoc -t -F Net/Squid/Auth/Plugin/SimpleLDAP.pm > $readme ) \
  || exit 1
[ "$dry_run" -eq 0 ] && git add README

msg "== Running ./Build.PL"
perl ./Build.PL || exit 1

msg "== Creating META.yml"
./Build distmeta || exit 1
git add META.yml

version=$(perl -nle 'if( /^version/ ) { s/^\S+\s+v//; print; }' META.yml)
msg "== Version: $version"

msg "== Generating <Changes> automagically"
changes=Changes
[ "$dry_run" -eq 1 ] && changes=/dev/tty
cp Changes __changes && {
    echo "Revision history for Net-Squid-Auth-Plugin-SimpleLDAP"
    echo ""
    printf '%-7s %s\n' "$version" "$(date +%d.%m.%Y)"
    git log --oneline | perl -nle 'next if /DIST VERSION '"$version"'/; exit if /DIST VERSION/; print "        $_";' &&
    echo "" &&
    cat __changes | perl -e '$a=<>; $a=<>; while(<>) { print }'
} > $changes \
  || exit 1
[ "$dry_run" -eq 0 ] && git add Changes

msg "== Committing files to git"
[ "$dry_run" -eq 0 ] && { git commit -m "DIST VERSION $version" || exit 1; }

msg "== Making distribution package"
./Build dist || exit 1

d=$(echo Net-Squid-Auth-Plugin-SimpleLDAP*.tar.gz) 
msg "== Moving file $d to home directory"
[ "$dry_run" -eq 0 ] && mv $d ${HOME}

msg "== Cleaning directory"
[ "$dry_run" -eq 0 ] && git clean -fd

